cleaning up remaining templates from #10918
mozilla/addons-server pull request #16336
Opened 2021-01-18 11:14 UTC by ankushduacodes

Fixes #16294

Changes Introduced:
-- Minor Template cleanup

(Opened early for the purpose of running tests)

2021-01-18 11:23 UTC, ankushduacodes commented
@eviljeff One of the tests are failing I am not sure why. But can confirm that this same error about `local_settings` import came up when I was trying to setup the dev env locally.

Any insight?

2021-01-18 14:40 UTC, eviljeff approved these changes
thanks r+

2021-01-18 14:54 UTC, eviljeff requested changes
sorry, we looked further into how the dependency (https://django-csp.readthedocs.io/en/latest/configuration.html) uses these settings and it appears that `CSP_FORM_ACTION` _does_ need to be defined, even when it's `"'self'"`.

2021-01-18 14:54 UTC, eviljeff commented on src/olympia/lib/settings_base.py
> -    'https://developer.mozilla.org',
actually, can we change this to just drop the `https:// ....` line, and keep the rest of the tuple as now.

2021-01-18 14:54 UTC, eviljeff commented on src/olympia/amo/tests/test_csp_headers.py
> -        assert "'self'" in base_settings.CSP_FORM_ACTION
and revert this line too

2021-01-19 09:37 UTC, eviljeff approved these changes
thanks! r+

2021-01-19 09:37 UTC, merged