Downgrade django.security.DisallowedHost logger to Warning
mozilla/addons-server pull request #16903
Opened 2021-04-09 12:29 UTC by wagnerand

Fix #16902.

2021-04-09 12:29 UTC, wagnerand commented on src/olympia/lib/settings_base.py
> +            'propagate': False,
Not sure if it should propagate or not.

2021-04-09 16:06 UTC, diox requested changes
That doesn't look correct - I don't think it'd work ? Nothing about this downgrades anything, it wouldn't have any impact.

I think if we want to go the downgrade route the proper way to do this would be a [python logging filter](https://docs.python.org/3/library/logging.html#logging.Filter.filter) attached to the config, but I'm not sure how this would interact with sentry integration, and it's a little annoying to write.

But maybe we don't need to! Instead, I think we should leave the logging config intact, don't downgrade the log, and just configure sentry: either using its [filtering callback](https://docs.sentry.io/platforms/python/guides/django/configuration/filtering/) or its API to [ignore specific loggers](https://docs.sentry.io/platforms/python/guides/logging/#ignoring-a-logger).

2021-04-09 16:29 UTC, wagnerand commented
You are right, I misread what `level` means.

Django specifically covers this behavior in the [documentation](https://docs.djangoproject.com/en/2.2/topics/logging/#django-security). Alternatively to use a python logging filter, we can also use a [django logging filter](https://docs.djangoproject.com/en/2.2/topics/logging/#id5).

Let me know what approach exactly we should pursue here.

2021-04-09 16:32 UTC, diox commented
I think the more robust solution is going to be the sentry approach, because ultimately that's the thing we care about.

2021-04-12 10:51 UTC, wagnerand commented
I found that the [python package](https://getsentry.github.io/sentry-python/api.html) supports passing `ignore_errors`, which looks simpler than using the filtering callback.

2021-04-12 11:50 UTC, diox requested changes
This doesn't seem to work.

From the docs, the recommended way is to use `ignore_logger`, which does seem to work.

```python
from sentry_sdk.integrations.logging import ignore_logger
(...)
ignore_logger('django.security.DisallowedHost')
```

(Placing the `ignore_logger(...)` after the `sentry_sdk.init` call)

2021-04-12 12:02 UTC, diox approved these changes

2021-04-12 12:26 UTC, merged