delete fake emails after 3 months
mozilla/addons-server pull request #17182
Opened 2021-05-19 14:11 UTC by iamvaishnav

Fixes #17122

2021-05-20 10:19 UTC, diox requested changes
Please don't change `jétpack.xpi` and also include a test for your changes.

2021-05-24 11:47 UTC, diox reviewed
Could you avoid renaming this file: 
`olympia/files/fixtures/files/jétpack.xpi → src/olympia/files/fixtures/files/jétpack.xpi`

It has a weird unicode filename (combining e and acute accent instead of a straight `é`) on purpose. Some git clients might have trouble with that, you might need to rebase and explicitly tell git to ignore that change.

2021-05-24 11:47 UTC, diox commented on src/olympia/amo/tests/test_cron.py
> +        assert FakeEmail.objects.count() == 1
Suggestion:

```suggestion
        assert FakeEmail.objects.count() == 1
        assert FakeEmail.objects.filter(pk=fe_new.pk).count() == 1
```

That way we also prove we deleted the right one.

2021-05-24 16:54 UTC, iamvaishnav commented
> Could you avoid renaming this file:
> `olympia/files/fixtures/files/jétpack.xpi → src/olympia/files/fixtures/files/jétpack.xpi`
> 
> It has a weird unicode filename (combining e and acute accent instead of a straight `é`) on purpose. Some git clients might have trouble with that, you might need to rebase and explicitly tell git to ignore that change.

Yeah, I've trouble with that

2021-05-25 10:45 UTC, diox approved these changes

2021-05-25 10:45 UTC, merged