Updated Message text
mozilla/addons-server pull request #17543
Opened 2021-07-21 16:48 UTC by NegiAkash890

Updated message text in "Submission Held for Review" emails to developers

Fixes  #17541

2021-07-21 17:22 UTC, wagnerand requested changes

2021-07-21 17:22 UTC, wagnerand commented on src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt
The greeting is already in the base template. Please remove it (and the blank lines) to resolve the duplication.

2021-07-21 17:22 UTC, wagnerand commented on src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt
> +
Same here, this is already part of the base template.

2021-07-26 13:27 UTC, wagnerand requested changes

2021-07-26 13:27 UTC, wagnerand commented on src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt
> +
Remove this blank line.

2021-07-26 13:27 UTC, wagnerand commented on src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt
> +If you are in urgent need of assistance not related to an add-on review, please contact amo-admins@mozilla.com
Add back blank line before this line.

2021-07-26 13:27 UTC, wagnerand commented on src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt
Remove this blank line.

2021-07-26 13:27 UTC, wagnerand commented on src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt
> +If you have questions around your add-on review, please reply to the reviewer email or leave a reply on the Developer hub, Manage Status & Versions page.
Add back blank line before this line.

2021-08-02 16:35 UTC, caitmuenster commented
Hey @NegiAkash890, you're really close to getting this one landed! Do you want to finish it off?

2021-08-03 17:05 UTC, NegiAkash890 commented
> Hey @NegiAkash890, you're really close to getting this one landed! Do you want to finish it off?

Sure, I will this one tomorrow !

2021-08-04 17:24 UTC, NegiAkash890 commented on src/olympia/reviewers/templates/reviewers/emails/held_for_review.ltxt
> +
Done!

2021-08-09 09:30 UTC, wagnerand commented
Hi @NegiAkash890, we'd like to get this out this week, so I am taking over here. Thank you for getting it started.

2021-08-09 09:52 UTC, closed without merging