Handle TypeError in abuse report serializer for non-string values
mozilla/addons-server pull request #21236
Opened 2023-09-27 21:12 UTC by shribyte

Fixes #19286

This PR addresses an issue where the abuse report API would throw a TypeError when certain fields received unexpected data types. The solution involves wrapping the problematic code block with a try-except to handle the TypeError and raising a more specific ValidationError.

The change has been successfully run and tested locally.

2023-09-28 08:44 UTC, diox requested changes
Please include a test for this change.

It can be a unit test in `src/olympia/abuse/tests/test_serializers.py` (in `TestAddonAbuseReportSerializer` class) or an integration test in `src/olympia/abuse/tests/test_views.py` (in `AddonAbuseViewSetTestBase`, which already has tests around method/source so it's probably the easiest)

2023-09-29 14:35 UTC, diox reviewed
This looks good, but as @eviljeff pointed out in the issue, if all the logic from `handle_unknown_install_method_or_source`() was moved into a `to_internal_value()` method on a custom class inheriting from `ReverseChoiceField` (that we would use instead of the normal `ReverseChoiceField` in the serializer when declaring `addon_install_method` and `addon_install_source` fields) we would be able to validate both separately, it would be slightly cleaner. Here because we're in the parent serializer, when the validation error is raised, we only return the first error (you can see that in the testcase you've added).

Bonus point, you could use `self.fail('invalid_choice', input=value)` instead of raising the exception and coming up with an error message yourself.

Let's get this PR merged and then you can do a follow-up separate PR for that refactor.

2023-09-29 14:35 UTC, diox commented on src/olympia/abuse/serializers.py
> +                {field_name: _('Invalid type for value submitted.')}
`'Invalid value'` is fine IMHO (we're already using that string elsewhere)

2023-09-29 14:51 UTC, shribyte commented
> This looks good, but as @eviljeff pointed out in the issue, if all the logic from `handle_unknown_install_method_or_source`() was moved into a `to_internal_value()` method on a custom class inheriting from `ReverseChoiceField` (that we would use instead of the normal `ReverseChoiceField` in the serializer when declaring `addon_install_method` and `addon_install_source` fields) we would be able to validate both separately, it would be slightly cleaner. Here because we're in the parent serializer, when the validation error is raised, we only return the first error (you can see that in the testcase you've added).
> 
> Bonus point, you could use `self.fail('invalid_choice', input=value)` instead of raising the exception and coming up with an error message yourself.

Got it, will split the refactoring into a future PR.

2023-09-29 15:06 UTC, diox approved these changes

2023-09-29 15:06 UTC, merged