Drf-spectacular
mozilla/addons-server pull request #22478
Opened 2024-07-16 17:17 UTC by KevinMind

Fixes: mozilla/addons#ISSUENUM

### Description

### Context

Notes:
- https://www.django-rest-framework.org/api-guide/filtering/
- https://github.com/axnsan12/drf-yasg/blob/d2cc0a348c2d9505a19e6ee7acea1e86fb63d277/testproj/users/views.py
- https://www.reddit.com/r/django/comments/12rspek/in_drf_do_you_validate_your_query_params_if_so_how/
- https://tinystruggles.com/posts/drf_recipes/#use-a-serializer-for-the-query-parameters
- https://django-filter.readthedocs.io/en/stable/guide/rest_framework.html

### Testing

### Checklist

- [ ] Add `#ISSUENUM` at the top of your PR to an existing open issue in the mozilla/addons repository.
- [ ] Successfully verified the change locally.
- [ ] The change is covered by automated tests, or otherwise indicated why doing so is unnecessary/impossible.
- [ ] Add before and after screenshots (Only for changes that impact the UI).
- [ ] Add or update relevant [docs](../docs/) reflecting the changes made.

2024-07-18 17:08 UTC, KevinMind commented
Fails test https://github.com/mozilla/addons-server/pull/3460. We can load the package via CDN but this seems bad for local development as you'd need a persistent internet connection..

2024-09-20 10:05 UTC, diox commented
Should I wait until https://github.com/mozilla/addons-server/pull/22663 is merged before reviewing this ? Or could you remove that commit (https://github.com/mozilla/addons-server/pull/22478/commits/6b9dbdc577321129fd68610aaba5cb43131bee93) ? It makes the diff a lot bigger and harder to follow.

2025-02-13 08:41 UTC, KevinMind commented
@diox Reviving this since it has been sitting here and there is nothing stopping its merge. It is bottom of the list in priority but enables some of the work I'm doing on the data retention policy since I want to add better documentation of some of the models.

2025-02-13 12:09 UTC, diox requested changes

2025-02-13 12:09 UTC, diox commented on src/olympia/lib/settings_base.py
> +    "'self'",
Err, that's a deal breaker. For prod, we absolutely don't want to allow `self` as a `script-src` in our CSP, that's too dangerous.

2025-03-10 19:51 UTC, KevinMind commented on src/olympia/lib/settings_base.py
> +    "'self'",
Another option, we can exclude `/api` or some subset of that from CSP... those URLs are not "really" relevant for CSP anyway right? Or are we worried about host spoofing code on specifically that subset.. can you explain in more detail the set of security vulnerabilities we are trying to defend against so it's easier to find a solution that meets the requirement?

2025-03-10 20:06 UTC, diox commented on src/olympia/lib/settings_base.py
> +    "'self'",
We're worried about any XSS on AMO domain, which would have typical wide consequences that XSS can have: stealing cookies, creating fake pages misleading users, etc.

This would be less likely on `/api/`... but still possible, in fact with swagger it's even more likely as it makes us host HTML content...

A strict CSP on all our responses is a non-negotiable requirement. If anything it should be stricter on `/api/` given that `/api/` shouldn't host anything that needs to load content (we gave up on it a while ago because it was low priority, but we did consider that at some point: https://github.com/mozilla/addons/issues/1855).

2025-03-11 13:55 UTC, KevinMind commented on src/olympia/lib/settings_base.py
> +    "'self'",
I've got another workaround which is handling this file the way we handle javascript catalog files. Currently the "dev" version generating on demand is working, but the management command to statically generate for production is failing.. in our production nginx, are requests to /static that are not resolved by our static assets bucket forwarded to django? I guess not right. That would really simplify this because then I could just handle it dynamically every time and call it a day.

2025-03-11 14:11 UTC, diox commented on src/olympia/lib/settings_base.py
> +    "'self'",
No fallback no. It's a bit messy, it goes through a CDN config and then nginx, ideally it would be CDN + Google Cloud Storage instead (as is already the case for addons-frontend static files), so I would rather not rely on adding a fallback mechanism.

2025-03-11 16:11 UTC, KevinMind commented on src/olympia/lib/settings_base.py
> +    "'self'",
I think I got it.. let's see. We have a per version url path based on /static/js/swagger/{version}.js. IN dev, this is rendered on the fly and during the build we pre generate each version in the static-build dir which should be collected and thus available in prod.

2025-03-11 16:16 UTC, KevinMind commented on src/olympia/lib/settings_base.py
> +    "'self'",
Works.

2025-03-12 12:59 UTC, diox commented on src/olympia/lib/settings_base.py
> +    "'self'",
You still have 'self' allowed though ?

2025-03-14 11:01 UTC, KevinMind commented on src/olympia/lib/settings_base.py
> +    "'self'",
Fixed. hopefully the verification still passes 🙃

2025-03-14 12:22 UTC, diox commented
Can you fix the conflicts too?

2025-03-14 19:52 UTC, KevinMind commented
@diox ready to go.

2025-03-17 17:03 UTC, diox commented
Multiple test failures https://github.com/mozilla/addons-server/actions/runs/13864297054/job/38799990651?pr=22478

2025-03-20 15:00 UTC, diox commented on src/olympia/amo/tests/test_csp_headers.py
> -        assert "'self'" not in base_settings.CSP_SCRIPT_SRC
Keep this

2025-03-20 15:03 UTC, diox commented on src/olympia/api/urls.py
> +
Should this be there? This is duplicated from what's in `get_versioned_api_routes()` except without the versioning

2025-03-20 15:04 UTC, diox commented on src/olympia/schema.py
> +            'description': 'pase the sessionId cookie as "Session {token}"',
```suggestion
            'description': 'pass the sessionId cookie as "Session {token}"',
```

2025-03-20 21:45 UTC, diox approved these changes

2025-03-20 21:49 UTC, merged