Graphviz
mozilla/addons-server pull request #22483
Opened 2024-07-17 12:42 UTC by KevinMind

- more up to date
- supports openapi spec v3
- supports doc string parsing and more explicit customizations

Fixes: mozilla/addons#ISSUENUM

### Description

### Context

### Testing

### Checklist

- [ ] Add `#ISSUENUM` at the top of your PR to an existing open issue in the mozilla/addons repository.
- [ ] Successfully verified the change locally.
- [ ] The change is covered by automated tests, or otherwise indicated why doing so is unnecessary/impossible.
- [ ] Add before and after screenshots (Only for changes that impact the UI).
- [ ] Add or update relevant [docs](../docs/) reflecting the changes made.

2025-05-15 15:42 UTC, KevinMind commented
> Where is `docs/_static/panzoom.min.js` coming from ? Should it be installed through `npm`'s `devDependencies` ?

I'm not totally sure how to do that with sphinx and it seemed easier to have an offline version rather than using a CDN.

2025-05-15 15:58 UTC, diox commented
Definitely don't want to depend on a CDN version, but we should make sure we can update it, rebuild it etc. Also obey licensing.

We're already installing npm dependencies in the image, so why can't we use that ? Even just copying the built file from `node_modules/panzoom/dist` when building docs would be enough.

2025-05-16 15:43 UTC, diox requested changes
(re-request when done fixing)

2025-05-16 17:48 UTC, KevinMind commented
WDYT, I actually think the graph generated by GraphViz is better than the one by django-model-info

### GraphViz

<img width="860" alt="Screenshot 2025-05-16 at 19 45 44" src="https://github.com/user-attachments/assets/63c95dd7-585a-4603-bd0a-eb7927039bbc" />

### Django Model Info

<img width="1679" alt="Screenshot 2025-05-16 at 19 38 15" src="https://github.com/user-attachments/assets/713c4aa0-5d85-495c-8970-7e5207d99f43" />

2025-05-16 18:25 UTC, KevinMind commented
@diox done

2025-05-16 18:29 UTC, diox commented
> WDYT, I actually think the graph generated by GraphViz is better than the one by django-model-info

Agreed

2025-05-19 11:16 UTC, diox approved these changes

2025-05-19 11:38 UTC, merged