Modify Button Behaviour When enable-submissions Flag is Disabled
mozilla/addons-server pull request #22779
Opened 2024-10-17 18:27 UTC by chrstinalin

Fixes: mozilla/addons#15090

### Description
when `enable-submissions` is disabled, now:
1. Disables the 'create a theme' button 
2. Addon submission buttons are disabled and a warning is displayed directly under them with the flag note.

![image](https://github.com/user-attachments/assets/31ccdb58-3bfa-4e1e-b128-dee767f521f3)

### Context

### Testing

### Checklist

- [x] Add `#ISSUENUM` at the top of your PR to an existing open issue in the mozilla/addons repository.
- [x] Successfully verified the change locally.
- [ ] The change is covered by automated tests, or otherwise indicated why doing so is unnecessary/impossible.

2024-10-18 19:36 UTC, KevinMind commented
@chrstinalin could you reassign review. I'll be on PTO next week and don't want to block you.

2024-10-21 09:01 UTC, eviljeff reviewed
I might be missing some context here, but why are we doing the disabling, and rendering the error, in javascript?  We know submissions are disabled when the template is rendered so add the logic to disable the buttons and display the message in the template?

We can test the error message is visible and the button disabled in tests too that way

2024-10-29 14:16 UTC, chrstinalin commented
I honestly can't recall if I had a reason for this, I think it may have been the natural progression of my original barebones fix... I do like that solution better, though

2024-10-30 12:27 UTC, eviljeff reviewed
Some nits in the test code, and it works fine.  I want to get a second opinion on the UI though - exposing the reason in a tooltip you have to mouse-over to seee feels too hidden to me.  ~Can you include a screenshot of what it looks like for reference?~ (you've already included one)

2024-10-30 13:04 UTC, diox commented
I'm no UX/Product person but I think it should be a bit more obvious. My idea was to prevent submissions while at the same time still showing a page that looks somewhat normal, because the error page you otherwise get from the decorator is a bit too generic/empty (it's good as a fallback for anyone trying to bypass the more user-friendly error).

2024-10-30 13:12 UTC, chrstinalin commented
@diox My initial fear with directly putting the reason on the page is if the reason is longer than usual (which may not happen) and possibly look weird. 

Though IIRC there's somewhere in DevHub that use a banner-style information section, which might work better? I can't seem to find it, though.

2024-10-30 13:26 UTC, diox commented
Search for `site-notice` (it displays the content of the `zadmin.models.Config` named `site_notice` which can be set in the admin)

2024-10-31 13:18 UTC, eviljeff requested changes

2024-10-31 13:18 UTC, eviljeff commented on src/olympia/devhub/views.py
> +    )
Can you add a test to verify what's rendered when there is no note set, but the flag is enabled?  I missed that case before.

2024-10-31 13:18 UTC, eviljeff commented on src/olympia/devhub/views.py
> +        'Add-on uploads are temporarily unavailable' + ': ' + flag.note
we need a `gettext` here too, or the warning won't be localised.

2024-10-31 13:38 UTC, eviljeff approved these changes

2024-10-31 13:40 UTC, merged