Allow Multiple Partner Addons
mozilla/addons-server pull request #22888
Opened 2024-11-24 15:45 UTC by chrstinalin

Fixes: mozilla/addons#ISSUENUM

### Description

### Context

### Testing

### Checklist

- [ ] Add `#ISSUENUM` at the top of your PR to an existing open issue in the mozilla/addons repository.
- [ ] Successfully verified the change locally.
- [ ] The change is covered by automated tests, or otherwise indicated why doing so is unnecessary/impossible.
- [ ] Add before and after screenshots (Only for changes that impact the UI).
- [ ] Add or update relevant [docs](../docs/) reflecting the changes made.

2024-12-05 10:40 UTC, KevinMind commented
So to be clear:

> Note: Frontend breaks without

Means the frontend PR should land first. right?

2024-12-05 10:45 UTC, diox commented
> Means the frontend PR should land first. right?

Yes, and as discussed during our stand-up, we should consider pushing the frontend changes for the 2024.12.12 push but *not* the addons-server changes, which are a lot more risky and should wait until next year (can land after the tag).

2024-12-09 14:50 UTC, willdurand commented on src/olympia/addons/serializers.py
> +            obj.promoted = [
This requires an update to the docs: https://mozilla.github.io/addons-server/topics/api/overview.html#v5-api-changelog

2024-12-09 14:53 UTC, willdurand commented on src/olympia/addons/serializers.py
> +            obj.promoted = []
ditto (IIUC this means the API cannot return `null` anymore)

2025-01-07 13:34 UTC, KevinMind commented
@chrstinalin is this PR still ready for review? I haven't seen or done anything since before the break so can you give a 👍 👎 if it is ready?

2025-01-22 09:51 UTC, KevinMind commented
@chrstinalin any update on this one?

2025-01-29 12:55 UTC, KevinMind commented on src/olympia/addons/models.py
> +        except ValueError:
Why would we expect a value error here? Can you add a comment for why that would happen?

2025-01-29 12:56 UTC, KevinMind commented on src/olympia/addons/models.py
> +        """Returns the string name of the currently groups, comma separated.
typo "currently"

2025-01-31 15:08 UTC, KevinMind submitted a review, later dismissed
Looking good so far. Some comments.

2025-01-31 19:31 UTC, chrstinalin commented on src/olympia/addons/models.py
> +    def promoted_groups(self, *, currently_approved=True):
So the complication is with `PromotedAddon`. In `promoted_groups()`, we filter on `approved_applications`. Since `approved_applications` is a `@property` function, Django would be [unable to filter by this property](https://forum.djangoproject.com/t/django-filter-can-it-handle-property-attributes/13808). In which case a loop similar to how it's implemented in this PR is done.

However, this means that a Manager on PromotedAddon couldn't be accessed (as we're returning a list), and so I'm not confident a query manager would work out.

2025-02-03 15:35 UTC, chrstinalin commented on src/olympia/addons/models.py
> +            if not currently_approved or promoted.approved_applications
This should actually the most elegant solution. Since `not currently_approved` is additive (if `true`, we include _all_ groups) we'd still need to loop through all the `promoted_addons` to get all the groups associated with the add-on.

i.e the alternative would be
``` 
return [promoted.group for promoted in promoted_addons] if not currently_approved else 
       [promoted.group for promoted in promoted_addons if promoted.approved_applications]
```

2025-02-04 09:52 UTC, KevinMind requested changes
My current feeling on the PR is that something is off. This touches so much of the code base and includes a pretty large migration I don't feel confident shipping in the current state. Spid-ey senses are triggering with:
- the get method and its return signature feels like the wrong abstraction. The name is confusing and the fact it returns three totally different and incompatible types just feels like a recipe for headache. I'd like to look at how we are using this to see if we can simplify that abstraction.
- The promoted_group field is used in many places and since we have a big migration, we should try to find a way to break this down. Maybe we can create a new field with the new type, and add the behavior we want around it. Then after we are happy with the behavior we can migrate the data and remove the old field. This makes it a lot safer to push changes because you don't necessarily break the whole data model if you make a mistake.

What you could definitely do now is open a PR that includes a mgiration adding "promoted_groups" as a foreign key type and logic in the model to sync the fields. When we modify the promoted_group field, also add that group to the promoted_groups. Now we have the new field and we can freely play around with it and find the right solution to this problem.

I know you are probably pretty anxious to get this merged and it has been tossed around a lot even since last year. But I'd rather not merge something that 1) has such a big impact and that 2) is hard to revert and 3) adds significant complexity top an already extremely complex code base.

2025-02-14 19:06 UTC, closed without merging