Support Markdown in Add-on Listing Fields
mozilla/addons-server pull request #22956
Opened 2024-12-20 21:05 UTC by chrstinalin

Fixes: mozilla/addons#15145

### Description

### Context

### Testing

### Checklist

- [ ] Add `#ISSUENUM` at the top of your PR to an existing open issue in the mozilla/addons repository.
- [ ] Successfully verified the change locally.
- [ ] The change is covered by automated tests, or otherwise indicated why doing so is unnecessary/impossible.
- [ ] Add before and after screenshots (Only for changes that impact the UI).
- [ ] Add or update relevant [docs](../docs/) reflecting the changes made.

2024-12-30 14:51 UTC, chrstinalin commented
There should probably be a more informative way to explain what syntax or Markdown is supported, possibly similar to how GitHub explains it via the 'Markdown is Supported' button by navigating to a [dedicated page](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

2025-01-07 13:27 UTC, KevinMind reviewed
Looks promising. A few comments before testing.

2025-01-07 13:27 UTC, KevinMind commented on src/olympia/translations/models.py
> +class PurifiedMarkdownTranslation(PurifiedTranslation):
Let's cover this with tests.

2025-01-07 13:27 UTC, KevinMind commented on src/olympia/devhub/templates/devhub/includes/macros.html
> +      _('Allowed Markdown: %(allowed_markdown)s', allowed_markdown='links, abbr,  bold, italics, blockquote, code, ol, ul')
allowed_markdown should be in a constant somewhere. If these are in fact the only tags allowed then use that same constant in actual processing.

2025-01-07 13:27 UTC, KevinMind commented on src/olympia/devhub/templates/devhub/includes/macros.html
> +{% macro markdown_tip(title=None) %}
I like what you have done elsewhere migrating from "html" to "syntax" let's do that here also "supported_syntax_tip" is a more generic name that won't again need to be migrated and encapsulates what you mean about markdown without coupling the name to the language.

2025-01-07 13:27 UTC, KevinMind commented on src/olympia/translations/models.py
> +        markdown = md.markdown(text_with_brs, extensions=['abbr', 'fenced_code'])
It's not clear why we are passing an array with "abbr" and "fenced_code" here.. can you add a comment?

2025-01-07 13:28 UTC, KevinMind commented
Please add testing steps and I can verify the PR.

2025-01-07 17:04 UTC, chrstinalin commented on src/olympia/devhub/templates/devhub/includes/macros.html
> +      _('Allowed Markdown: %(allowed_markdown)s', allowed_markdown='links, abbr,  bold, italics, blockquote, code, ol, ul')
Just since you pointed this out --

> There should probably be a more informative way to explain what syntax or Markdown is supported, possibly similar to how GitHub explains it via the 'Markdown is Supported' button by navigating to a [dedicated page](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

I mentioned this to Andrew offhandedly as, especially with the extensions, it may not be obvious what Markdown syntax is allowed in what way, and he mentioned maybe making it a page on the extension workshop over the tooltip. What do you think?

2025-01-09 10:33 UTC, KevinMind commented on src/olympia/devhub/templates/devhub/includes/macros.html
> +      _('Allowed Markdown: %(allowed_markdown)s', allowed_markdown='links, abbr,  bold, italics, blockquote, code, ol, ul')
I'm definitely in favor of that yes. I don't think it is directly related to my ask though. I want to make sure that the tags specified in this tooltip are "bound" to the tags we actually filter for, so that if one were to change, the other is automatically synced.

It would be a bad UX if the tooltip allowed links, but actually we don't. Would it be possible to extract this list to a constant and the `", ".join(ALLOWED_MARKDOWN_TAGS)` in the template?

And then where we actually validate the input, we can use the same constant.

2025-01-09 10:36 UTC, KevinMind commented on src/olympia/translations/tests/test_models.py
> +class PurifiedMarkdownTranslationTest(TestCase):
nit: Typically I think adding `Test` to the beginning is better than the end as this class now matches the class it is testing in a find/replace

<img width="416" alt="image" src="https://github.com/user-attachments/assets/5164e1f3-f111-4500-9e92-accccf00efc7" />

2025-01-09 10:39 UTC, KevinMind commented
@chrstinalin what should I expect to happen if I enter invalid or disallowed markdown syntax? Can you add that to the test scenario. Additionally can you clarify what "functional" means? I think you mean the syntax should be "rendered" on the page right?

2025-01-09 10:45 UTC, KevinMind commented on src/olympia/translations/tests/test_models.py
> +
Can you add a test of mixed html and markdown, simulating someone editing an existing html string and adding markdown to it. We would expect the html to be stringified and the markdown to be formatted to html right?

2025-01-09 10:45 UTC, KevinMind commented on src/olympia/devhub/templates/devhub/includes/macros.html
> +      _('Allowed Markdown: %(allowed_markdown)s', allowed_markdown='links, abbr,  bold, italics, blockquote, code, ol, ul')
It looks like we have such a constant in the translations model file already "allowed_tags"

2025-01-09 14:25 UTC, chrstinalin commented on src/olympia/translations/tests/test_models.py
> +
`test_markdown` does have a case of mixed HTML and markdown, and yeah -- the HTML is stringified, the markdown is formatted.

2025-01-09 14:29 UTC, chrstinalin commented on src/olympia/devhub/templates/devhub/includes/macros.html
> +      _('Allowed Markdown: %(allowed_markdown)s', allowed_markdown='links, abbr,  bold, italics, blockquote, code, ol, ul')
I had meant it in a replace-the-tooltip-entirely way, but I figure there's no harm in having both.

2025-01-20 09:50 UTC, KevinMind commented on src/olympia/translations/tests/test_models.py
> +
ah I missed that in the name `test_mixed_markdown_html` maybe?

2025-01-20 10:40 UTC, KevinMind commented
After modifying existing html I can confirm:
- before modification the html is rendered
- after the modification it is stringified

<img width="504" alt="image" src="https://github.com/user-attachments/assets/fe54c47e-0dd3-42dc-a513-57a404a50c06" />

Should we expect the "stringified" href attribute to still be rendered as a link though? it is.. I'm not sure if that is expected or not.

2025-01-20 10:41 UTC, KevinMind commented
I'm seeing a template tag instead of actually allowed markdown tags

<img width="336" alt="image" src="https://github.com/user-attachments/assets/11142239-0bda-4283-94e7-81ede24c6529" />

2025-01-20 10:42 UTC, KevinMind commented
Do I still expect to see html supported for version notes?

<img width="833" alt="image" src="https://github.com/user-attachments/assets/d7328792-db54-442a-a07d-d058c52c9f10" />

2025-01-20 10:43 UTC, KevinMind commented
@chrstinalin I cannot find the developer comments section.. can you help navigating there?

2025-01-20 10:44 UTC, KevinMind commented
There is no way to preview content in the authors page. I can add markdown but after saving I still see the textarea so I have no idea what it would actually render as

<img width="726" alt="image" src="https://github.com/user-attachments/assets/b73f2fd4-361d-4361-bcc7-bb3f55e12c73" />

2025-01-20 10:48 UTC, KevinMind commented
@chrstinalin something that would be very helpful when verifying this is if you could share a sample of both html and markdown that include a sample of all the supported tags.

I even wonder if having this available to developers on a page could be useful. There are many flavors of markdown and looking at the tag, it's hard for me (with context) to know what and how I should input the syntax to get the expected result.

Imagine how difficult it would be for a developer.

2025-01-20 10:48 UTC, KevinMind requested changes
Still needs some work. A few bugs discovered and some edge cases needing addressing.

Also found a UX hangup that might be worth addressing in terms of usability of this feature.

2025-01-20 13:48 UTC, chrstinalin commented
> Should we expect the "stringified" href attribute to still be rendered as a link though? it is.. I'm not sure if that is expected or not.

Currently, if you were to put just a link in, it'd render similarly. If we're essentially treating user HTML as plaintext from now on, I can't see why this wouldn't be expected?

> Do I still expect to see html supported for version notes?

I had omitted it originally since it wasn't part of the original issue. Now that I think about it, though, there's probably no reason to do that. @abyrne-moz should add-on version notes also make the switch from HTML to Markdown?

> I cannot find the developer comments section.. can you help navigating there?

At the very bottom of 'Edit Product Page', under 'Technical Details'.

> There is no way to preview content in the authors page. I can add markdown but after saving I still see the textarea so I have no idea what it would actually render as

As it did with HTML before, too. It did bother me, though. It shouldn't hurt to just add the rendering.

> something that would be very helpful when verifying this is if you could share a sample of both html and markdown that include a sample of all the supported tags.

```
Some of these words *are emphasized*.
Some of these words _are emphasized also_.

Use two asterisks for **strong emphasis**.
Or, if you prefer, __use two underscores instead__.

Here's a link: [Google](https://www.google.com "Click me!").

**abbr, acronym**

The HTML specification is maintained by the W3C.
*[HTML]: Hyper Text Markup Language
*[W3C]:  World Wide Web Consortium

**codeblocks, blockquotes**

Here is code:

    tell application "Foo"
        beep
    end tell

> This is the first level of quoting.
> > This is nested blockquote.

**Lists**

*Ordered List:*

1. First item
2. Second item
3. Third item

*Unordered List:*

- Item 1
- Item 2
- Item 3

This is an [example link](http://example.com/)

<a href="www.google.com">This shouldnt work!</a>

<ol>
<li>Neither</li>
<li>Should</li>
<li>This</li>
</ol>
```

> I even wonder if having this available to developers on a page could be useful. There are many flavors of markdown and looking at the tag, it's hard for me (with context) to know what and how I should input the syntax to get the expected result.

Yeah, which is why I mentioned it [before](https://github.com/mozilla/addons-server/pull/22956#discussion_r1905792997). Though I imagined something like:
1) Merge this PR
2) Merge a PR to `extension-workshop` with syntax information
3) Create a PR to link to said information.
Being a smoother way about it?

2025-01-20 19:01 UTC, KevinMind commented
Thanks for the updates. Everything checks out except this part:

> Currently, if you were to put just a link in, it'd render similarly. If we're essentially treating user HTML as plaintext from now on, I can't see why this wouldn't be expected?

If I render this on a browser:

```
<html>
<body>
<a href="http://github.com/mozilla/addons-server">
Github repo
</a>
</body>
</html>
```

I do not expect a clickable link to appear on the screen. I expect (just like github is doing, to just render out all the markup as plain text.

I kind of have the same expectations for our "plain text" html where we render links. As you can see the html syntax is rendered as plain text, but somehow, the link is a clickable link.. that seems odd.

Is that actually expected behaviour? why plaint text the links then?

2025-01-20 21:06 UTC, chrstinalin commented
I do agree its a bit weird. But I'd still say its expected as a result of the [linkify](https://github.com/mozilla/addons-server/blob/52b004f660cf8bc8823839f33428d2aa87507822/src/olympia/translations/models.py#L213) bleach converting [any string that looks like a URL](https://bleach.readthedocs.io/en/latest/linkify.html#bleach.linkify).

2025-01-22 09:24 UTC, KevinMind commented
Do you mean the "whiteboard" if that also supports markdown I would expect the same tooltip we have in the other inputs.

<img width="765" alt="image" src="https://github.com/user-attachments/assets/366b7ecf-55b1-4de4-a8f1-a5d37d9a4e62" />

2025-01-22 09:56 UTC, KevinMind approved these changes
Verified the specified input sources as correctly formatting markdown and plaint text ifying html

<img width="741" alt="image" src="https://github.com/user-attachments/assets/82b07a21-ab0e-4fad-8621-aba82c720233" />

2025-01-27 15:09 UTC, merged